remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme 

title: [A scoping Delphi study for the co-development of a clinical visual grading system for female genital schistosomiasis]
description: [Information sheet]
